### PR TITLE
added protoc binaries for protobuf 3.0.0 to protoc-bundled-plugin

### PR DESCRIPTION
**Pull request by mikesamuel**
The latest non-beta release is https://github.com/google/protobuf/releases/tag/v3.0.0

This adds the protoc binaries for that release using https://github.com/comoyo/commons/commit/c6c1d6d3acb92786bef7a52699eff23722557138 as a template so that an invocation of the protoc-bundled-plugin by a project that depends on `com.google.protobuf:protobuf-java:3.0.0` can use a non-beta protoc.

----

I extracted these binaries by doing:

```sh
curl -L -O https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_32.zip
curl -L -O https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip
curl -L -O https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-osx-x86_64.zip
curl -L -O https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-osx-x86_32.zip
curl -L -O https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-win32.zip
unzip -p protoc-3.0.0-linux-x86_32.zip bin/protoc > protoc-3.0.0-linux-x86
unzip -p protoc-3.0.0-linux-x86_64.zip bin/protoc > protoc-3.0.0-linux-x86_64
unzip -p protoc-3.0.0-osx-x86_64.zip bin/protoc > protoc-3.0.0-mac_os_x-x86_64
unzip -p protoc-3.0.0-osx-x86_32.zip bin/protoc > protoc-3.0.0-mac_os_x-x86
unzip -p protoc-3.0.0-win32.zip bin/protoc.exe > protoc-3.0.0-win32-x86.exe
rm *.zip
```

### CODE REVIEW

**Comment by comoyouser** [comment]
Can one of the admins verify this patch?

**Comment by argggh** [comment]
Thanks for this, good that someone pays attention. :)

**Comment by argggh** [comment]
Released as 1.4.56.

**Comment by mikesamuel** [comment]
Thanks

**Pull request merged**
